server:
  port: 9002

spring:
  application:
    name: UMS-EMPLOYEE-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #zipkin:
   # base-url: http://127.0.0.1:9411/   
#The below is added in git repository as part of UMS MS Config Server and not required here      
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

#spring:
#  application:
#    name: USER-SERVICE
#  zipkin:
#    base-url: http://127.0.0.1:9411/
