server:
  port: 9002

spring:
  application:
    name: UMS-EMPLOYEE-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: manager
    url: jdbc:postgresql://localhost:5432/umsadmindb
    #url: jdbc:postgresql://10.10.1.224:5432/users
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
app:
   clientId: 1fae0a6f-23c3-4762-91c9-950f9921885e
   clientSecret: Up38Q~8Vt8KoQcVIojw_eFb0d0FCZmD.Kr4s0ccr
   tenantId: d467e766-3a5c-4382-b9ba-4f8bb30e9d3c
  #zipkin:
   # base-url: http://127.0.0.1:9411/   
#The below is added in git repository as part of UMS MS Config Server and not required here      
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

#spring:
#  application:
#    name: USER-SERVICE
#  zipkin:
#    base-url: http://127.0.0.1:9411/
